var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "             xxx                     xxx                j                       ",
   "                    xxx     xx      xx!xx      xx      xx         xxxx          ",
   "       xx                           x!!!x                            x   &      ",
   "       xx                           xxvxx                            x          ",
   "       xx                                                            x        o ",
   "       xxxxx                                    o  o                 x          ",
   "  xxxxxxxxxxxxxxxxxx                                                 x       xxx",
   "  x                x o                                               x o     x  ",
   "  x                xx                                o  &            x       x  ",
   "  x                x        xxxx    xxxxx    o       xxxxxxx         xxx  &  x  ",
   "  x                xxxxx                    xxx                      x       x  ",
   "  x                                                           o      x       x  ",
   "  x                     o                                    xxx o   x       x  ",
   "  x                                                                  x   o   x  ",
   "  x          xxxx       o                                         o  x       x  ",
   "  x  @       x!!x       &                &                           x   D   x  ",
   "  xxxxxxxxxxxx!!xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x                  x     x                    ",
   "  xxx        xxxx             x!!!x                  x!!!!!x                    ",
   "  xxx        xxxx             x!!!x                  x!!!!!x                    ",
   "  xxx        xxxx             xxxxx                  xxxxxxx                    ",
   "  xxx        xxxx                                                               ",
   "  xxx        xxxx                                                               "],
  ["                                                                                                                  ",
   "                                               x!!                                                                ",
   "                                               xx!!!                                                              ",
   "                                               xxxx!!!!!!!!!!!!!!!!!!!!!!                                         ",
   "                                               xxxxxxxxxxxxxxxxxxxxxxxxxvxxxxxxx                                  ",
   "                                               x                     x         x                                  ",
   "                                               x                     x     o   xxxxxxxxxxxxxxx                    ",
   "                                               x                     x                       x                    ",
   "                                               x             o       x     x                 x                    ",
   "                                               x                     x     x                 x                    ",
   "                                               x                     x     x                 x                    ",
   "                                               x       o             xo    x                 x!!!!!!!!!!!!        ",
   "                                               x     xxx             xx    x                 xxxxxxxxxxxxx        ",
   "                                               x     x               x     x                             x        ",
   "                           o                   x     x               x     x     o                       x        ",
   "                                               xx    x               x    ox                             x        ",
   "                               o               x     x               x    xx!!!!xx    o      xxxxxxx  &  x        ",
   "               xxxxxxx  o     xxx o xxx        x     x           o   x     x!!!!x            xxxxxxx     x        ",
   "              xx     xx         x   x          x     x               x     xxxxxx     o      x     x     x        ",
   "            xxx       xxx       x o x          x    xx               xo         x            x           x        ",
   "     @       x         x        x   x          x     x               xx         x   xxxxx    x           x        ",
   "xxxxxxxxxxxxxx         x        x   x          x     x               x          x            x     o  &  x        ",
   "    x x      x         x       xx o xx         x     x               x          x!!!!!!!!!!!!x   xxxxxxxxx        ",
   "xxxxx xxxxxxxx         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x          x!!!!!!!!!!!!x  &        x        ",
   "    x x      x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!  o  xxxxxx     xxxxxxxxxxxxxx           x        ",
   "    x x      x         x!!!!!x    o                 xx!!!!!!xx !                x              o         x        ",
   "    x x      x         x!!!!!x                     xx!!!!!!xx  v              xxx                        x        ",
   "    x x      x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx       o            x           o            x        ",
   "    x x      x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx                     x    D                   x        ",
   "    x x      x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                              x               ",
   "                                                                                              x               ",
   "                                                                                 o  o      D  x               ",
   "                                                                                    xxxxxxxxxxx               ",
   "                                                                               o                              ",
   "                                                                                                              ",
   "                                                                               o                              ",
   "                                                                                                              ",
   "                                                                               o                              ",
   "                                                                            j                                 ",
   "                                                                         xxxxxxx                              ",
   "                                                                        &                                     ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                       x                                      ",
   "                                                                        &                                     ",
   "                        o                                                                                     ",
   "                                                                                                              ",
   "                                           x                             x                                    ",
   "                    o       o        &     xx                                                                 ",
   "                                    xx     xxx  x                                                             ",
   "                   x                       xxxx xx                     xxx                                    ",
   "                            xxxx           xxxxxxxx                                                           ",
   "                o                          xxxxxxxxx                                                          ",
   "                                           xxxxxxxxxx                                                         ",
   "                x                          xxxxxxxxxxxxxxxxxxx    xxxx                                        ",
   "                x  o                                         x                                                ",
   "                x                                            x                                                ",
   "                x  x   o                      o              x                                                ",
   "                x  x                                         x                                                ",
   "                x  x   xx       o         o                  x                                                ",
   "                x  x   xx      xxx     xxxxx      o          x                                                ",
   "                x  x   xx       x          x        @        x                                                ",
   "                x  x   xx       x          x      xxxxx      x                                                ",
   "                x  x   xx !!!!!!x!!!!!!!!!!x      x!!!x      x!!!!!!!!!!!!!!!!!                               ",
   "!!!!!!!!!!!!!!!!x!!x!!!xx!xxxxxxxxxxxxxxxxxx     xx!!!xx     xxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
  ["                                                                                               ",
   "                                                                                               ",
   "                                                                                               ",
   "                                                                                               ",
   "                 xxxxxxxx x   x   xx   x     x x   x xxxx                                      ",
   "                    x     x   x  x  x  xx    x x  x  x  x                                      ",
   "                    x     x   x x    x x x   x x x   x                                         ",
   "                    x     xxxxx x    x x  x  x xx    xxxx                                      ",
   "                    x     x   x xxxxxx x   x x x x      x                                      ",
   "                    x     x   x x    x x    xx x  x  x  x                                      ",
   "                    x     x   x x    x x     x x   x xxxx                                      ",
   "                                    !  !                                                       ",
   "                                    !!!!                                                       ",
   "                                       !                                                       ",
   "                oooooo  o        oo   o!     o o o     o oooooo                                ",
   "                o     o o       o  o   o    o  o oo    o o    o                                ",
   "                o     o o      o    o   o  o   o o o   o o    o                                ",
   "                oooooo  o      o    o    oo    o o  o  o o                                     ",
   "                o       o      oooooo    oo    o o   o o o oooo                                ",
   "                o       o      o    o    oo    o o    oo o    o                                ",
   "                o       oooooo o    o    oo    o o     o oooooo                                ",
   "  @                                                                                             ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
   
  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
